Repository BHoM/Rhinoceros_Toolkit, pull requests merged in 2020-05, with the labels that each got.

#157 Fixing copy local set to false and build folder for release
  Rhinoceros_Engine/Rhinoceros_Engine.csproj
Labels: type:compliance

#161 Fix crash on invalid mesh preview in Rhino
  Rhinoceros_Engine/Convert/ToRhino.cs
Labels: type:bug

#162 Align readme to new guidelines
  README.md
Labels: type:documentation

#159 Update following changes in the oM for PlanarSurface
  Rhinoceros_Engine/Convert/FromRhino.cs
Labels: type:external-api-changes
